# Generated by Django 2.1 on 2018-08-25 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_myuser_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_answer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='myuser',
            name='is_student',
            field=models.BooleanField(default=True),
        ),
    ]
